# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task --list

  _clean:
    aliases: [c]
    desc: Clean up
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: _clean-mac

  _clean-mac:
    internal: true
    platforms: [darwin]
    cmds:
      - find . -type d -name ".terraform" -prune -exec rm -rf {} +
      - find . -name ".DS_Store" -delete
      - find . -name ".terraform.lock.hcl" -delete
      - find . -name "terraform.tfstate" -delete
      - find . -name "terraform.tfstate.backup" -delete

  _license:
    desc: "Work with product licensing"
    cmds:
      - uv run cml license show

  _ls:
    aliases: [l]
    desc: "Lists running labs and optionally those in the cache"
    cmds:
      - uv run cml ls

  upload-iamge:
    internal: true
    cmds:
      - uv run cml definitions images import image-file -f {{.IMG_FILE}}
      - uv run cml definitions images import definition -f {{.IMG_DEF}}

  # A10 vThunder

  a10vthunder:
    desc: "A10 vThunder (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/a10vthunder/node/a10vthunder.yaml

  a10vthunder-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/a10vthunder/vThunder_{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/a10vthunder/image/a10vthunder_{{.IMG_VER}}.yaml"

  a10vthunder_6_0_6_83:
    desc: "A10 vThunder 6.0.6.83"
    cmds:
      - task: a10vthunder-image
        vars:
          IMG_VER: "6_0_6_83"

  # Aruba-CX

  aruba-cx:
    desc: "Aruba-CX (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/aruba-cx/node/aruba-cx.yaml

  aruba-cx-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/aruba-cx/ArubaOS-CX_{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/aruba-cx/image/aruba-cx_{{.IMG_VER}}.yaml"

  aruba-cx-10_04_1000:
    desc: "Aruba-CX 10_04_1000"
    cmds:
      - task: aruba-cx-image
        vars:
          IMG_VER: "10_04_1000"

  # F5 BIG-IP VE

  f5-bigip-ve:
    desc: "F5 BIG-IP VE (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/f5-bigip-ve/node/f5-bigip-ve.yaml

  f5-bigip-ve-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/f5-bigip-ve/BIGIP-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/f5-bigip-ve/image/f5-bigip-ve-{{.IMG_VER}}.yaml"

  f5-bigip-ve-17.0.0-0.0.22:
    desc: "F5 BIG-IP VE 17.0.0-0.0.22"
    cmds:
      - task: f5-bigip-ve-image
        vars:
          IMG_VER: "17.0.0-0.0.22"

  # FortiGate

  fortigate:
    desc: "FortiGate (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/fortigate/node/fortigate.yaml

  fortigate-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/fortinet/fortigate/fortios-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/fortigate/image/fortigate-{{.IMG_VER}}.yaml"

  fortigate-7.0.1:
    desc: "FortiGate 7.0.1"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.1"

  fortigate-7.0.6:
    desc: "FortiGate 7.0.6"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.6"

  fortigate-7.0.8:
    desc: "FortiGate 7.0.8"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.8"

  fortigate-7.0.19:
    desc: "FortiGate 7.0.19"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.19"

  fortigate-7.2.0:
    desc: "FortiGate 7.2.0"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.2.0"

  fortigate-7.2.2:
    desc: "FortiGate 7.2.2"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.2.2"

  fortigate-7.2.4:
    desc: "FortiGate 7.2.4"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.2.4"

  fortigate-7.4.1:
    desc: "FortiGate 7.4.1"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.4.1"

  fortigate-7.4.4:
    desc: "FortiGate 7.4.4"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.4.4"

  fortigate-7.4.11:
    desc: "FortiGate 7.4.11"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.4.11"

  fortigate-7.6.1:
    desc: "FortiGate 7.6.1"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.6.1"

  fortigate-7.6.6:
    desc: "FortiGate 7.6.6"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.6.6"

  # ThousandEyes-VA

  thousandeyes-va:
    desc: "ThousandEyes-VA (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/thousandeyes-va/node/thousandeyes-va.yaml

  thousandeyes-va-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/cisco/te/thousandeyes-va-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/thousandeyes-va/image/thousandeyes-va-{{.IMG_VER}}.yaml"

  thousandeyes-va-0.263.0:
    desc: "ThousandEyes-VA 0.263.0"
    cmds:
      - task: thousandeyes-va-image
        vars:
          IMG_VER: "0.263.0"

  # Ubuntu

  ubuntu-22-04-20260515:
    desc: "Ubuntu 22-04-20260515"
    cmds:
      - uv run cml definitions images import image-file -f {{.DOC_ROOT}}/ubuntu/jammy-server-cloudimg-amd64.qcow2
      - uv run cml definitions images import definition -f definitions/ubuntu/image/ubuntu-22-04-20260515.yaml

  ubuntu-24-04-20260518:
    desc: "Ubuntu 24-04-20260518"
    cmds:
      - uv run cml definitions images import image-file -f {{.DOC_ROOT}}/ubuntu/noble-server-cloudimg-amd64.qcow2
      - uv run cml definitions images import definition -f definitions/ubuntu/image/ubuntu-24-04-20260518.yaml

  ubuntu-26-04-20260520:
    desc: "Ubuntu 26-04-20260520"
    cmds:
      - uv run cml definitions images import image-file -f {{.DOC_ROOT}}/ubuntu/resolute-server-cloudimg-amd64.qcow2
      - uv run cml definitions images import definition -f definitions/ubuntu/image/ubuntu-26-04-20260520.yaml

  # Ubuntu-Extra

  ubuntu-extra:
    desc: "Ubuntu-Extra (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/ubuntu-extra/node/ubuntu-extra.yaml

  ubuntu-extra-24-04-20260323:
    desc: "Ubuntu-Extra 24-04-20260323"
    cmds:
      - uv run cml definitions images import image-file -f {{.DOC_ROOT}}/ubuntu/noble-server-cloudimg-amd64-extra-20260323.qcow2
      - uv run cml definitions images import definition -f definitions/ubuntu-extra/image/ubuntu-extra-24-04-20260323.yaml

  ubuntu-extra-24-04-20260518:
    desc: "Ubuntu-Extra 24-04-20260518"
    cmds:
      - uv run cml definitions images import image-file -f {{.DOC_ROOT}}/ubuntu/noble-server-cloudimg-amd64-extra-20260518.qcow2
      - uv run cml definitions images import definition -f definitions/ubuntu-extra/image/ubuntu-extra-24-04-20260518.yaml

  # vJunos-Switch

  vjunos-switch:
    desc: "vJunos-Switch (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/vjunos-switch/node/vjunos-switch.yaml

  vjunos-switch-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/juniper/vJunos-switch-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/vjunos-switch/image/vjunos-switch-{{.IMG_VER}}.yaml"

  vjunos-switch-24.4R1.9:
    desc: "vJunos-Switch 24.4R1.9"
    cmds:
      - task: vjunos-switch-image
        vars:
          IMG_VER: "24.4R1.9"

  vjunos-switch-25.2R1.9:
    desc: "vJunos-Switch 25.2R1.9"
    cmds:
      - task: vjunos-switch-image
        vars:
          IMG_VER: "25.2R1.9"

  # Windows11

  win11:
    desc: "Windows11 (Node)"
    cmds:
      - uv run cml definitions nodes import -f definitions/win11/node/win11.yaml

  win11-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/windows/11_{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/win11/image/win11_{{.IMG_VER}}.yaml"

  win11_en-us_26100-240331-1435:
    desc: "Windows11 en-us 26100-240331-1435"
    cmds:
      - task: win11-image
        vars:
          IMG_VER: "en-us_26100-240331-1435"

  win11_ja-jp_26100-240331-1435:
    desc: "Windows11 ja-jp 26100-240331-1435"
    cmds:
      - task: win11-image
        vars:
          IMG_VER: "ja-jp_26100-240331-1435"
