# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task --list

  _clean:
    aliases: [c]
    desc: Clean up
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: _clean-mac

  _clean-mac:
    internal: true
    platforms: [darwin]
    cmds:
      - find . -type d -name ".terraform" -prune -exec rm -rf {} +
      - find . -name ".DS_Store" -delete
      - find . -name ".terraform.lock.hcl" -delete
      - find . -name "terraform.tfstate" -delete
      - find . -name "terraform.tfstate.backup" -delete

  _license:
    desc: "Work with product licensing"
    cmds:
      - uv run cml license show

  _ls:
    aliases: [l]
    desc: "Lists running labs and optionally those in the cache"
    cmds:
      - uv run cml ls

  upload-iamge:
    internal: true
    cmds:
      - uv run cml definitions images import image-file -f {{.IMG_FILE}}
      - uv run cml definitions images import definition -f {{.IMG_DEF}}

  # A10 vThunder

  a10vthunder:
    desc: "Import A10 vThunder node definition"
    cmds:
      - uv run cml definitions nodes import -f definitions/a10vthunder/node/a10vthunder.yaml

  a10vthunder-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/a10vthunder/vThunder_{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/a10vthunder/image/a10vthunder_{{.IMG_VER}}.yaml"

  a10vthunder_6_0_6_83:
    desc: "Import A10 vThunder 6.0.6.83 image"
    cmds:
      - task: a10vthunder-image
        vars:
          IMG_VER: "6_0_6_83"

  # Aruba-CX

  aruba-cx:
    desc: "Import Aruba-CX node definition"
    cmds:
      - uv run cml definitions nodes import -f definitions/aruba-cx/node/aruba-cx.yaml

  aruba-cx-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/aruba-cx/ArubaOS-CX_{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/aruba-cx/image/aruba-cx_{{.IMG_VER}}.yaml"

  aruba-cx-10_04_1000:
    desc: "Import Aruba-CX 10_04_1000 image"
    cmds:
      - task: aruba-cx-image
        vars:
          IMG_VER: "10_04_1000"

  # F5 BIG-IP VE

  f5-bigip-ve:
    desc: "Import F5 BIG-IP VE node definition"
    cmds:
      - uv run cml definitions nodes import -f definitions/f5-bigip-ve/node/f5-bigip-ve.yaml

  f5-bigip-ve-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/f5-bigip-ve/BIGIP-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/f5-bigip-ve/image/f5-bigip-ve-{{.IMG_VER}}.yaml"

  f5-bigip-ve-17.0.0-0.0.22:
    desc: "Import F5 BIG-IP VE 17.0.0-0.0.22 image"
    cmds:
      - task: f5-bigip-ve-image
        vars:
          IMG_VER: "17.0.0-0.0.22"

  # FortiGate

  fortigate:
    desc: "Import FortiGate node definition"
    cmds:
      - uv run cml definitions nodes import -f definitions/fortigate/node/fortigate.yaml

  fortigate-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/fortinet/fortigate/fortios-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/fortigate/image/fortigate-{{.IMG_VER}}.yaml"

  fortigate-7.0.1:
    desc: "Import FortiGate 7.0.1 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.1"

  fortigate-7.0.6:
    desc: "Import FortiGate 7.0.6 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.6"

  fortigate-7.0.8:
    desc: "Import FortiGate 7.0.8 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.8"

  fortigate-7.0.19:
    desc: "Import FortiGate 7.0.19 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.0.19"

  fortigate-7.2.0:
    desc: "Import FortiGate 7.2.0 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.2.0"

  fortigate-7.2.2:
    desc: "Import FortiGate 7.2.2 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.2.2"

  fortigate-7.2.4:
    desc: "Import FortiGate 7.2.4 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.2.4"

  fortigate-7.4.1:
    desc: "Import FortiGate 7.4.1 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.4.1"

  fortigate-7.4.4:
    desc: "Import FortiGate 7.4.4 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.4.4"

  fortigate-7.4.11:
    desc: "Import FortiGate 7.4.11 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.4.11"

  fortigate-7.6.1:
    desc: "Import FortiGate 7.6.1 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.6.1"

  fortigate-7.6.6:
    desc: "Import FortiGate 7.6.6 image"
    cmds:
      - task: fortigate-image
        vars:
          IMG_VER: "7.6.6"

  # ThousandEyes-VA

  thousandeyes-va:
    desc: "Import ThousandEyes node definition"
    cmds:
      - uv run cml definitions nodes import -f definitions/thousandeyes-va/node/thousandeyes-va.yaml

  thousandeyes-va-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/cisco/te/thousandeyes-va-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/thousandeyes-va/image/thousandeyes-va-{{.IMG_VER}}.yaml"

  thousandeyes-va-0.263.0:
    desc: "Import ThousandEyes-VA 0.263.0 image"
    cmds:
      - task: thousandeyes-va-image
        vars:
          IMG_VER: "0.263.0"

  # vJunos-Switch

  vjunos-switch:
    desc: "Import vJunos-Switch node definition"
    cmds:
      - uv run cml definitions nodes import -f definitions/vjunos-switch/node/vjunos-switch.yaml

  vjunos-switch-image:
    internal: true
    cmds:
      - task: upload-iamge
        vars:
          IMG_FILE: "{{.DOC_ROOT}}/juniper/vJunos-switch-{{.IMG_VER}}.qcow2"
          IMG_DEF: "definitions/vjunos-switch/image/vjunos-switch-{{.IMG_VER}}.yaml"

  vjunos-switch-25.2R1.9:
    desc: "Import vJunos-Switch 25.2R1.9 image"
    cmds:
      - task: vjunos-switch-image
        vars:
          IMG_VER: "25.2R1.9"
